import { NewsArticleDto } from "../news/news.dto";
import { NewsletterResponseDto } from "./newsletter.dto";

export class NewsletterGenerator {
    public generate(
        articles: NewsArticleDto[]
    ): NewsletterResponseDto {

        return {
            date: new Date().toISOString().split("T")[0],
            generatedAt: new Date().toISOString(),
            articles: articles.map((article, index) => ({
                id: index + 1,
                title: article.title,
                summary: article.description,
                whyDoesThisMatterToMe:
                    "This section will later be generated by AI for a web developer.",
            })),
        };
    }
}